// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.email.server.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EmailMessageBuilder extends
		EmailMessageBuilderBase<EmailMessageBuilder> {
	public static EmailMessageBuilder emailMessage() {
		return new EmailMessageBuilder();
	}

	public EmailMessageBuilder() {
		super(new EmailMessage());
	}

	public EmailMessage build() {
		return getInstance();
	}
}

class EmailMessageBuilderBase<GeneratorT extends EmailMessageBuilderBase<GeneratorT>> {
	private EmailMessage instance;

	protected EmailMessageBuilderBase(EmailMessage aInstance) {
		instance = aInstance;
	}

	protected EmailMessage getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withAddresseeList(List<String> aValue) {
		instance.setAddresseeList(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withAddedAddresseeListElement(String aValue) {
		if (instance.getAddresseeList() == null) {
			instance.setAddresseeList(new ArrayList<String>());
		}

		((ArrayList<String>) instance.getAddresseeList()).add(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withId(Long aValue) {
		instance.setId(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withSubject(String aValue) {
		instance.setSubject(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withMessage(String aValue) {
		instance.setMessage(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withResponseName(String aValue) {
		instance.setResponseName(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withResponseEmail(String aValue) {
		instance.setResponseEmail(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withSendingDate(Date aValue) {
		instance.setSendingDate(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withAttachmentDownloadURLs(List<String> aValue) {
		instance.setAttachmentDownloadURLs(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withAddedAttachmentDownloadURL(String aValue) {
		if (instance.getAttachmentDownloadURLs() == null) {
			instance.setAttachmentDownloadURLs(new ArrayList<String>());
		}

		((ArrayList<String>) instance.getAttachmentDownloadURLs()).add(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withSendingFailureNotificationURL(String aValue) {
		instance.setSendingFailureNotificationURL(aValue);

		return (GeneratorT) this;
	}
}
