package com.email.server.save.entities;

// Generated 2015-06-23 11:29:22 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AddresseeList generated by hbm2java
 */
@Entity
@Table(name = "addressee_list", catalog = "email_sender")
public class AddresseeList implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1866413000342339023L;
	private Long id;
	private Email email;
	private String addressee;

	public AddresseeList() {
	}

	public AddresseeList(String addressee) {
		this.addressee = addressee;
	}

	public AddresseeList(Email email, String addressee) {
		this.email = email;
		this.addressee = addressee;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "email_id", referencedColumnName = "id", nullable = false)
	public Email getEmail() {
		return this.email;
	}

	public void setEmail(Email email) {
		this.email = email;
	}

	@Column(name = "addressee", nullable = false, length = 100)
	public String getAddressee() {
		return this.addressee;
	}

	public void setAddressee(String addressee) {
		this.addressee = addressee;
	}

}
