package com.email.server.save.entities;

// Generated 2015-06-23 11:29:22 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AttachmentDownloadUrls generated by hbm2java
 */
@Entity
@Table(name = "attachment_download_urls", catalog = "email_sender")
public class AttachmentDownloadUrls implements java.io.Serializable {

	private static final long serialVersionUID = 1317087652176142639L;
	private Long id;
	private Email email;
	private String url;

	public AttachmentDownloadUrls() {
	}

	public AttachmentDownloadUrls(String url) {
		this.url = url;
	}

	public AttachmentDownloadUrls(Email email, String url) {
		this.email = email;
		this.url = url;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "email_id", referencedColumnName = "id", nullable = false)
	public Email getEmail() {
		return this.email;
	}

	public void setEmail(Email email) {
		this.email = email;
	}

	@Column(name = "url", nullable = false, length = 256)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
